spring:
  jpa:
    hibernate:
      ddl-auto: update # DB 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 pretty print
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect # 이게 포함되어있어야 jts Geometry -> DB GEOMETRY type으로 생성됩니다.
    #    show-sql: true # SQL 쿼리 출력
    open-in-view: true
    defer-datasource-initialization: true # hibernate의 auto schema creation(ddl-auto) 이후에 schema.sql, data.sql실행
  sql:
    init:
      mode: always # embedded database(ex h2) 이외에도 항상 sql을 실해하도록 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  config: classpath:logback-spring.xml

server:
  servlet:
    encoding:
      force-response: true # MockMVC 테스트에서 응답에 한글이 깨지는 현상 해결 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.server.server.servlet.encoding.force-response

jwt:
  secret-key: ${JWT_SECRET_KEY_EXERCISE}
  access-token-expiration-minutes: 240
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false