spring:
  jpa:
    hibernate:
      ddl-auto: update # DB 스키마 자동 생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  key:
    secret: ${JWT_SECRET_KEY_EXERCISE}
  access-token-expiration-minutes: 240
  refresh-token-expiration-minutes: 420